export const ROUTES = {
  ROOT: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  DASHBOARD: "/dashboard",
  VENDORS: "/vendors",
  VENDORS_NEW: "/vendors/new",
  VENDOR_DETAIL: "/vendors/:id",
  RFQS: "/rfqs",
  RFQS_NEW: "/rfqs/new",
  RFQ_DETAIL: "/rfqs/:id",
  RFQ_EDIT: "/rfqs/:id/edit",
  RFQ_COMPARE: "/rfqs/:id/compare",
  QUOTATIONS: "/quotations",
  QUOTATIONS_NEW: "/rfqs/:rfq_id/quotations/new",
  QUOTATION_DETAIL: "/quotations/:id",
  APPROVALS: "/approvals",
  APPROVAL_DETAIL: "/approvals/:id",
  PURCHASE_ORDERS: "/purchase-orders",
  PURCHASE_ORDER_DETAIL: "/purchase-orders/:id",
  INVOICES: "/invoices",
  INVOICE_DETAIL: "/invoices/:id",
  REPORTS: "/reports",
  ACTIVITY: "/activity",
};